### ISSUE TITLE
Do you plan on supporting FLAC format?

### ISSUE THREAD

**Issue by WhiteAngel69** [ShinyId3Tagger/Shiny-ID3-Tagger#11]
Vorbis comments on .FLAC

**Comment by ShinyId3Tagger** [comment]
Im using taglib-sharp to access and modify ID3 tags. 

I have to look into it if it has the same methods as the original taglib (https://taglib.org/) to handle vorbis comments (which is the way to add metadata to FLAC files)

**Comment by rluvaton** [comment]
As I can see the library we use support FLAC files, @WhiteAngel69 do you have a problem using it with FLAC files?

**Comment by rluvaton** [comment]
I guess the answer to this question was given and we can close this issue.
