### ISSUE TITLE
Editing tags manually

### ISSUE THREAD

**Issue by rluvaton** [ShinyId3Tagger/Shiny-ID3-Tagger#23]
Maybe let's add the feature to write tags to song manually

**Comment by rluvaton** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add User option to choose from tags service manually for each file](https://trello.com/c/ot54Erqh/6-add-user-option-to-choose-from-tags-service-manually-for-each-file)

**Comment by ShinyId3Tagger** [comment]
sounds good to me. I'll upload a UI mockup on how to edit them manually. I wanna hear your opinion then

**Comment by rluvaton** [comment]
> sounds good to me. I'll upload a UI mockup on how to edit them manually. I wanna hear your opinion then

@ShinyId3Tagger Any updates?

**Comment by horacecar** [comment]
Hello ShinyId3Tagger , i really like your program, and really want the manually fuction, for example i can choose the source is from spotify or itunes , and the size of the cover , will you updates this good program, i will very looking forward to hear from you again.

**Comment by horacecar** [comment]
hello,  @ShinyId3Tagger  , then how about manually select the artist , title, genre, album from specified source ? still Pretending update"?

**Comment by horacecar** [comment]
@rluvaton never mind. Take just take the time you guys need.... i will come check every day. Because this program really helps me a lot if have the program can manually select artists or album from specific sources. Thank you. :)

**Comment by ShinyId3Tagger** [comment]
I really wanna continue working on this project. but I need to find the
time. my new full time job takes most of it.

manual selection is on top of the Todo list

Am Do., 31. Jan. 2019, 15:48 hat horacecar <notifications@github.com>
geschrieben:

**Comment by horacecar** [comment]
Never mind you can just take your time .  I’m really really really looking for it.

**Comment by rluvaton** [comment]
@horacecar You can contribute to make this faster...

**Comment by rluvaton** [comment]
@horacecar Yes

**Comment by horacecar** [comment]
Actually i am thinking maybe we can do it in a easy way ? maybe we can let the program to read the txt config file first, for example 
---------start---------------
config: 

source :
{
spotify
itunes
amazon
}
--------------end-------------------
then the result will sort the mostly result , if three of their genre is different, then the result will show the first one 's genre which is spotify.

if the txt config file is like that, 
-----------start-------------
config: 

source :
{
amazon
}
----------------end-----------------

then the result will show the music information from amazon directly ,

**Comment by rluvaton** [comment]
@horacecar This feature is added in the `v1.5-alpha` pre-release

For editing the tag you need to press `F2` and click the cell you wanna edit
